log:
  level: trace
ssl_cert_dir: "/path/to"
central:
  pollInterval: 10s
  url: https://central.eu-fr.axway.com
  organizationID:
  environment:
  auth:
    clientID: DOSA_
    privateKey: "/path/to/private_key.pem"
    publicKey: "/path/to/public_key.pem"
  subscriptions:
    notifications:
      type:
        - smtp
      smtp:
        host: smtp.host.com
        port: 587
        fromAddress: sender@your-domain.com
        username: your_user_name
        password: password
        subscribe:
          body: >
            <p>A Subscription just got created for AsyncAPI {{.CatalogItemName}}.</p>Detailed description of the AsyncAPI can get found at: <a href={{.CatalogItemURL}}">Axway Central {{.CatalogItemName}} </a> <p></p><p>The subscribed AsyncAPI is secured with <ul><li>Username: <b> {{.ClientID}} </b></li><li>Password: <b> {{.ClientSecret}} </b></li></ul></p>
          oauth: >
            </br></a>Your API is secured using Username: <b> {{.ClientID}} </b> and Password=<b> {{.ClientSecret}} </b>
        unsubscribe:
          body: >
            <p>A Subscription just got unsubscribed for AsyncAPI {{.CatalogItemName}}.</p>Detailed description of the AsyncAPI can get found at: <a href={{.CatalogItemURL}}">Axway Central {{.CatalogItemName}} </a> <p>

connector:
  url: http://some..location/v1
  adminUser:
  adminPassword:
  orgUser:
  orgPassword:
  acceptinsecurecertificates:

notifier:
  enabled: true
  url: http://some.location
  apiConsumerKey: key_or_username
  apiConsumerSecret: secret_or_password
  acceptinsecurecertificates: false
  #basic / header
  apiAuthType: basic