log:
  level: trace
ssl_cert_dir: "/path/to"
central:
  pollInterval: 10s
  url: https://central.eu-fr.axway.com
  organizationID:
  environment:
  auth:
    clientID: DOSA_
    privateKey: "/path/to/private_key.pem"
    publicKey: "/path/to/public_key.pem"

connector:
  url: http://some..location/v1
  adminUser:
  adminPassword:
  orgUser:
  orgPassword:
  acceptinsecurecertificates:

notifier:
  url: http://some.location
  apiConsumerKey: key_or_username
  apiConsumerSecret: secret_or_password
  acceptinsecurecertificates: false
  #basic / header
  apiAuthType: basic