openapi: 3.0.0
info: 
  title: Solace Axway Agent Subscription Distribution
  description: 'Distributes Subscribe and Unsubscribe Events'
  version: 0.1.0
  
servers:
  - url: /notifier
    description: Axway Integration Builder Sandbox

paths:
  /health:
    post:
      summary: Publishes a message to check access of service
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/HealthEvent"

      responses:
        '200':
          description: Ok
        '400':
          description: Bad formatted content
        '403':
          description: Forbidden
  /subscribe:
    post:
      summary: Publishes Subscribe Information
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/NotificationSubscribeEvent"

      responses:
        '200':
          description: Ok
        '400':
          description: Bad formatted content
        '403':
          description: Forbidden
  /unsubscribe:
    post:
      summary: Publishes Unsubscribe Information
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/NotificationUnsubscribeEvent"
      responses:
        '200':
          description: Ok
        '400':
          description: Bad formatted content
        '403':
          description: Forbidden
  /monitor/success:
    post:
      summary: Monitoring information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MonitoringEvent"
      responses:
        '200':
          description: Ok
        '400':
          description: Bad formatted content
        '403':
          description: Forbidden

  /monitor/failure:
    post:
      summary: Monitoring information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MonitoringEvent"
      responses:
        '200':
          description: Ok
        '400':
          description: Bad formatted content
        '403':
          description: Forbidden

components:
  schemas:
    HealthEvent:
      type: object
      required:
        - echo
      properties:
        echo:
          type: string
    MonitoringEvent:
      type: object
      required:
        - specversion
        - type
        - source
        - id
        - time
        - datacontenttype
        - data
      properties:
        specversion:
          type: string
        type:
          type: string
          enum:
            - "com.solace.iot-team.asyncapi.notification.monitor.v1"
        source:
          type: string
        id:
          type: string
        time:
          type: string
        datacontenttype:
          type: string
          enum:
            - "application/json"
        data:
          $ref: '#/components/schemas/MonitorData'

    MonitorData:
      type: object
      required:
        - trigger
        - success
        - correlationId
        - environment
        - team
        - api
        - product
        - application
        - subscription
        - subscriber
        - subscriberEmail
        - applicationData
        - asyncApis
      properties:
        trigger:
          type: string
          enum:
            - subscribe
            - unsubscribe
        success:
          type: boolean
        correlationId:
          type: string
        message:
          type: string
        environment:
          type: string
        team:
          type: string
        api:
          type: string
        product:
          type: string
        application:
          type: string
        subscription:
          type: string
        subscriber:
          type: string
        subscriberEmail:
          type: string

    NotificationSubscribeEvent:
      type: object
      required:
        - specversion
        - type
        - source
        - id
        - time
        - datacontenttype
        - data
      properties:
        specversion:
          type: string
        type:
          type: string
          enum: 
            - "com.solace.iot-team.asyncapi.notification.subscribe.v1"    
        source:
          type: string
        id:
          type: string
        time:
          type: string
        datacontenttype:
          type: string
          enum: 
            - "application/json"
        data:
          $ref: '#/components/schemas/SubscribeData'
    SubscribeData:
      type: object
      required:
        - environment
        - team
        - api
        - product
        - application
        - subscription
        - subscriber
        - subscriberEmail
        - applicationData
        - asyncApis
      properties:
        environment:
          type: string
        team: 
          type: string
        api: 
          type: string
        product:
          type: string
        application:
          type: string
        subscription:
          type: string
        subscriber: 
          type: string
        subscriberEmail:
          type: string
        applicationData:
          type: object
        asyncApis:
          type: array
          items: 
            type: object
    NotificationUnsubscribeEvent:
      type: object
      required:
        - specversion
        - type
        - source
        - id
        - time
        - datacontenttype
        - data
      properties:
        specversion:
          type: string
        type:
          type: string
          enum: 
            - "com.solace.iot-team.asyncapi.notification.unsubscribe.v1"    
        source:
          type: string
        id:
          type: string
        time:
          type: string
        datacontenttype:
          type: string
          enum: 
            - "application/json"
        data:
          $ref: '#/components/schemas/UnsubscribeData'
    UnsubscribeData:
      type: object
      required:
        - environment
        - team
        - api
        - product
        - application
        - subscription
        - subscriber
        - subscriberEmail
      properties:
        environment:
          type: string
        team: 
          type: string
        api: 
          type: string
        product:
          type: string
        application:
          type: string
        subscription:
          type: string
        subscriber: 
          type: string
        subscriberEmail:
          type: string

                      
      
              
          
            
  