name: main-build-workflow
on:
  # for testing
  workflow_dispatch:

  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          method: approle
          namespace: ${{ secrets.VAULT_NAMESPACE }}
          roleId: ${{ secrets.VAULT_ROLEID }}
          secretId: ${{ secrets.VAULT_SECRETID }}
          secrets: |
            secret/data/sol/async/agent/ci CENTRAL_ENVIRONMENT | CENTRAL_ENVIRONMENT ;
            secret/data/sol/async/agent/ci CENTRAL_ORGANIZATIONID | CENTRAL_ORGANIZATIONID
            secret/data/sol/async/agent/ci INVALID | INVALID

      - name: Print vault data CENTRAL_ENVIRONMENT
        run: echo ${{env.CENTRAL_ENVIRONMENT}} | sed 's/./& /g'

      - name: Print vault data INVALID
        run: echo ${{env.INVALID}} | sed 's/./& /g'

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.15'
      - run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: build it
        run: |
          make dep
          make build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      - uses: actions/checkout@v2

      - name: Set versions properties
        run:  |
          VERSION=$(<version)
          echo "VERSION=$VERSION">> $GITHUB_ENV
          echo "VERSION: $VERSION"

      - name: Build and Deploy to Docker registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            solaceiotteam/solace-axway-agent:alpha
            solaceiotteam/solace-axway-agent:${{env.VERSION}}