name: main-build-workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.15'
      - run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: build it
        run: |
          make dep
          make build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v2
      with:
        context: bin
        push: true
        tags: |
          solaceiotteam/solace-axway-agent:alpha
